### ISSUE TITLE
Hey Sorry to bother you

### ISSUE THREAD

**Issue by ProfessorBear** [Skepter/Superfight#1]
I was curious what the process would be to get this working, any help you could lend would be greatly appreciated. Thanks!

**Comment by JorelAli** [comment]
Thanks for the request - I evidently haven't written any proper documentation for running this which I should do when I get the chance.

To run the project:
* Clone the project (or download the .zip file of the project and unzip it) and open the Superfight folder. 
* If you don't have Node.js installed already, download and install it [from their site](https://nodejs.org/en/). 
* Open a command prompt/terminal in this location (i.e. in the Superfight folder) and install the required node modules by using the command `npm install`.
* To start the node.js server, run the command `node server.js`
* The IP endpoint will be displayed in the console (for me, it looked like `192.168.1.163:1337`)

For the project to load, two text files are required: `Attributes.txt` and `Characters.txt`:
* Create the files inside a folder called `Cards`, (so it should be `Superfight/Cards/Attributes.txt` and `Superfight/Cards/Characters.txt`)
* To add entries to these files, simply place each character/attribute on a separate line. As with Superfight, white cards are characters and black cards are attributes.

Multiple players on the same network should be able to access the game by using the stated IP from the console. When they "join" the game, they must enter a username and they are placed in a "room". When two players enter a room, they can begin the game.
